configure: don't support asm without memalign (PR #22233)
PR #22233 opened by Niklas Haas (haasn)
URL: https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/22233
Patch URL: https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/22233.patch

I tried it, and it broke horribly. We should definitively rule out this.

Unfortunately, it's not as easy as just setting `disable asm` here, because
asm having been enabled will already have affected the build process further
upstream - conversely, we don't know whether or not memalign exists until
fairly late in the build process, and I'm not about to go destroying
the current organization of the file just to work around this.

So an error message it is.

>From 5172ca3e9052f7e744c2030526f090a66095e16b Mon Sep 17 00:00:00 2001
From: Niklas Haas <git@haasn.dev>
Date: Fri, 20 Feb 2026 20:36:34 +0100
Subject: [PATCH] configure: don't support asm without memalign

I tried it, and it broke horribly. We should definitively rule out this.

Unfortunately, it's not as easy as just setting `disable asm` here, because
asm having been enabled will already have affected the build process further
upstream - conversely, we don't know whether or not memalign exists until
fairly late in the build process, and I'm not about to go destroying
the current organization of the file just to work around this.

So an error message it is.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8183,6 +8183,12 @@ haiku)
     ;;
 esac
 
+if enabled_any asm inline_asm; then
+    if ! enabled_any memalign posix_memalign; then
+        die "ERROR: At least one of memalign or posix_memalign must be enabled when using assembly code."
+    fi
+fi
+
 flatten_extralibs(){
     nested_entries=
     list_name=$1
